module.exports = [ //o começo não pode repetir
[['MI', 'FO'],200, 'Lapso da Fortuna'],
[['CI', 'EN'],200, 'Robótico'],
[['FE', 'EP'],200, 'Exército Peludo'],
[['CA', 'EP'],250, 'Aquele que Intesifica'],
[['FE', 'SO'],250, 'Breve Comando'],
[['FE', 'MI'],250, 'Filho do Monarca'],
[['MI', 'RE'],300, 'A Esquecida'],
[['BO', 'SO'],300, 'Jovem Deus Generoso'],
[['FO', 'MI', 'NU'],450, 'Os Exilados'],
[['MI', 'EN', 'FE'],450, 'A Prisão Quebrada'],
[['ET', 'NU', 'RO'],450, 'Amigos do Terceiro Rei'],
[['BO', 'ET', 'RO'],500, 'As Amantes do Império'],
[['RO', 'AN', 'MI'],500, 'Casal Desmanchado'],
[['FE', 'CI', 'AN'],600, 'Mentes sem Alma'],
[['RE', 'SO', 'MU'],600, 'Mortos pela História'],
[['BO', 'RO', 'LI', 'CA'],1000, 'Escolhidos da Majestade'],
[['FO', 'RO', 'EP', 'MU'],1000, 'Perdidos no Além'],
[['BO', 'AN', 'EP', 'MU', 'RE'],1500, 'Nação Destruída'],
[['EP', 'FE', 'RE', 'SO', 'LI'],1500, 'Guerreiros Caídos'],
[['RE', 'FE', 'SO', 'BO', 'LI'],2000, 'Os Donos'],
[['RE', 'EP', 'MU', 'EN', 'SO'],3000, 'Primal Rebewllion'],
]